<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.FileProviders.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.FileProviders.Physical" Version="10.0.12" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
    <PackageVersion Include="Octokit" Version="14.0.0" />
    <PackageVersion Include="AdvancedSharpAdbClient" Version="3.6.16" />
    <PackageVersion Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageVersion Include="System.IO.Abstractions" Version="22.2.0" />
    <PackageVersion Include="System.IO.Abstractions.TestingHelpers" Version="22.2.0" />
    <PackageVersion Include="TUnit" Version="1.68.17" />
  </ItemGroup>
</Project>
