<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Novolis.IO.Ndjson.Benchmarks</RootNamespace>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Novolis.IO.Ndjson/Novolis.IO.Ndjson.csproj" />
  </ItemGroup>
</Project>
